# Generated by Django 3.2 on 2021-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_friends_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='birth',
        ),
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=200),
        ),
    ]
